import tkinter as tk
from dataManager import Profile
from profilePage import profile_page
from createProfilePage import create_profile_page
from overviewPage import overview_page

# Remove all child widgets from window and returns the window
def clear_window(master):
	window = master
	while window.master != None:
		window = window.master

	for child in window.winfo_children():
		child.destroy()
	return window

# Loads the page generated by page_generator
def load_page(master, page_generator):
	window = clear_window(master)
	page = page_generator(window)
	page.pack(fill=tk.BOTH)

# Loads the profile with name name
# Master is the window to be cleared or some child of the window
# used in profilePage.profile_button
def load_overview_page(master, name):
	load_page(master, lambda master: overview_page(master, Profile(name)))

# Loads the create profile page
# master is the window to be cleared or some child of the window
def load_create_profile_page(master):
	load_page(master, create_profile_page)

# Loads the profile page
def load_profile_page(master):
	load_page(master, profile_page)
